### ISSUE TITLE
Configuration for WEIXIN_AUTH_BASE_URI is missing.

### ISSUE THREAD

**Issue by jhdxr** [SocialiteProviders/Weixin#6]
just followed all the steps written on http://socialiteproviders.github.io/providers/weixin/, and when I executed `composer install`, I got the following error:
```
 [SocialiteProviders\Manager\Exception\MissingConfigException]
  Configuration for WEIXIN_AUTH_BASE_URI is missing.
  There is no services entry for weixin
```

look into the source I found where `auth_base_url` is used and the default value is fine as well. btw, and I found #3 . I think either the config should be documented clearly or should be optional or removed. ( if it's impossible for now, then this is a bug and the issue should not be closed before fixed)

**Comment by jhdxr** [comment]
#3 says

>  Just leave it blank for now.

However, we cannot set `WEIXIN_AUTH_BASE_URI` to empty, `ConfigRetriever::getFromEnv` checks the value and if the value get from env == false, then an exception will be throwed.

**Comment by DraperStudio** [comment]
@jhdxr https://github.com/SocialiteProviders/Manager/commit/7282ff1a137b8b56655cfed3afc87035dd741902 https://github.com/SocialiteProviders/Manager/commit/6c99cb1725ac2b8e5358639bc0f3eb401dc33367

Additional config keys should now be spoofed **(set with null)** instead of throwing an exception. Try `composer update` and let me know if it works.

**Comment by jhdxr** [comment]
yes, the new version works for me. thanks for your work.

**Comment by DraperStudio** [comment]
The `v2.1.8` release has been removed for now since it was causing some other issues. I will take a closer look at this tomorrow and release a proper fix. Sorry for any inconvenience.

**Comment by DraperStudio** [comment]
@jhdxr Could you replace these files in your vendor directory? https://github.com/SocialiteProviders/Manager/commit/7c0c77be69e3ac6ce2b9ccb8f04e175322f8a3da
https://github.com/SocialiteProviders/Manager/commit/7bb2b7e66087f0f5d10b6d88963cefb6cdced52d

**Comment by jhdxr** [comment]
I replaced these files and `Provider::getAuthUrl()` is broken.

```php
        $this->getConfig(
            'auth_base_uri',
            'https://open.weixin.qq.com/connect/oauth2/authorize'
        )
```
returns null if `WEIXIN_AUTH_BASE_URI` not exists or set to empty in .env

**Comment by DraperStudio** [comment]
**Replace method in ConfigTrait.php**
```
    protected function getConfig($key = null, $default = null)
    {
        // check manually if a key is given and if it exists in the config
        // this has to be done to check for spoofed additional config keys so that null isn't returned
        if (!empty($key) && empty($this->config[$key])) {
            return $default;
        }
        return $key ? array_get($this->config, $key, $default) : $this->config;
    }
```

I am currently just on my phone so can't really look around a lot.

**Comment by jhdxr** [comment]
@DraperStudio it works.

**Comment by DraperStudio** [comment]
Great, I will merge the changes soon and tag a new release. Can take a bit since I am on my phone.

**Comment by jhdxr** [comment]
that's fine. could you ping me after you release the new version? thx

**Comment by DraperStudio** [comment]
@jhdxr https://github.com/SocialiteProviders/Manager/releases/tag/v2.1.8
