### ISSUE TITLE
scope problem

### ISSUE THREAD

**Issue by jhdxr** [SocialiteProviders/Weixin#7]
there three different scopes for weixin login. `snsapi_base` and `snsapi_userinfo` for mp.weixin.qq.com (login for pages inside wechat app), `snsapi_login` for open.weixin.qq.com (login for pages on pc). so there are two different package for weixin, this one and https://github.com/SocialiteProviders/Weixin-Web. 
IMO, I think this package is the first case. However a6353928d85dc5687b8ca80ddf6babc5132d0e71 changed the scope, without offering a method to set the scope. so is this a bug or by design?

**Comment by DraperStudio** [comment]
@jhdxr For Asian/Russian Providers we rely on information the users give us since most of these Services offer terrible English docs or none at all so if this was a mistake and should be reverted send a PR.

You should be able to set the scopes like this.
`return Socialite::driver('weixin')->scopes(['snsapi_base', 'snsapi_userinfo', 'snsapi_login'])->redirect();`

**Comment by jhdxr** [comment]
ok, I'll send a pr along with the docs introducing the difference between this two package.
but where should I put these docs? is there any example?

**Comment by DraperStudio** [comment]
What kind of docs would you need to add?

**Comment by DraperStudio** [comment]
@jhdxr Any progress?

**Comment by jhdxr** [comment]
@DraperStudio sorry for my late response. I'd like to introduce current situation and problem first.
Weixin, AKA Wechat, has provide 3 different ways to login.

the first case is used for login on pc. (doc: https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419316505&token=&lang=zh_CN) the scope is `snsapi_login` and the auth url is `https://open.weixin.qq.com/connect/qrconnect` . [SocialiteProviders/Weixin-Web](https://github.com/SocialiteProviders/Weixin-Web/blob/master/src/Provider.php) provide the support for this part, and I think the implement is correct.

the other two cases are used for login inside wechat app. (doc: http://mp.weixin.qq.com/wiki/4/9ac2e7b1f1d22e9e57260f6553822520.html) the available scope is `snsapi_base` or `snsapi_userinfo`, and the auth url is `https://open.weixin.qq.com/connect/oauth2/authorize`. Obviously [the implements here](https://github.com/SocialiteProviders/Weixin/blob/master/src/Provider.php) is wrong, as `snsapi_login` is not a valid option here, and it doesn't make sense to allow user to define the auth url. 
what's more, `->scopes()` can't fix this problem, because it's appending the params to the socpe rather than replacing it. for example, `snsapi_base` should get the basic info without user's permission. however, `->scopes(['snsapi_base'])` will lead redirect to a page asking for permission.

it seems it's easy to get confused which package should be used, for example, the qr code mentioned in #2 is used for login on pc, so IMHO he should use `SocialiteProviders/Weixin-Web` instead of this package. so I'd like to write something on docs to tell users how to distinguish the two packages.
