### ISSUE TITLE
Configuration for WEIXIN_AUTH_BASE_URI is missing. Missing services entry for weixin.auth_base_uri

### ISSUE THREAD

**Issue by chinayrzpin** [SocialiteProviders/Weixin#8]
Configuration for WEIXIN_AUTH_BASE_URI is missing.
Missing services entry for weixin.auth_base_uri

**Comment by chinayrzpin** [comment]
What's the problem?
'weixin' => [
        'client_id' => env('WEIXIN_KEY'),
        'client_secret' => env('WEIXIN_SECRET'),
        'redirect' => env('WEIXIN_REDIRECT_URI'),
    ],
The lack of configuration items?

**Comment by chinayrzpin** [comment]
Problem has been resolved，Modified to


'weixin' => [
        'client_id' => env('WEIXIN_KEY'),
        'client_secret' => env('WEIXIN_SECRET'),
        'redirect' => env('WEIXIN_REDIRECT_URI'),
        'auth_base_uri' => 'https://open.weixin.qq.com/connect/oauth2/authorize',
    ],


Why do you need to manually configure, should not automatically loading the default?


protected function getAuthUrl($state)
    {
        return $this->buildAuthUrlFromBase($this->getConfig(
            'auth_base_uri',
            'https://open.weixin.qq.com/connect/oauth2/authorize'
        ), $state);
    }


No loading right?

**Comment by DraperStudio** [comment]
Do a composer update and see if it works, this should have been fixed with v2.1.8 of the Manager.

**Comment by chinayrzpin** [comment]
Being updated, thank you for your timely answer
